import type { Category } from "@/types/oscar";

export const CATEGORIES: Category[] = [
  {
    id: "picture",
    number: "01",
    label: "MELHOR",
    title: "FILME",
    tmdbType: "movie",
    nominees: [
      { id: "secret-agent", name: "The Secret Agent", tmdbId: 1220564 },
      { id: "one-battle", name: "One Battle After Another", tmdbId: 1054867 },
      { id: "bugonia", name: "Bugonia", tmdbId: 701387 },
      { id: "f1", name: "F1", tmdbId: 911430 },
      { id: "frankenstein", name: "Frankenstein (2025)", tmdbId: 1062722 },
      { id: "hamnet", name: "Hamnet", tmdbId: 858024 },
      { id: "sinners", name: "Sinners", tmdbId: 1233413 },
      { id: "marty-supreme", name: "Marty Supreme", tmdbId: 1317288 },
      { id: "sentimental-value", name: "Sentimental Value", tmdbId: 1124566 },
      { id: "train-dreams", name: "Train Dreams", tmdbId: 1241983 },
    ],
  },
  {
    id: "director",
    number: "02",
    label: "MELHOR",
    title: "DIREÇÃO",
    tmdbType: "person",
    nominees: [
      { id: "zhao", name: "Chloé Zhao", subtitle: "Hamnet", tmdbId: 1395183 },
      { id: "safdie", name: "Josh Safdie", subtitle: "Marty Supreme", tmdbId: 129561 },
      {
        id: "pta",
        name: "Paul Thomas Anderson",
        subtitle: "One Battle After Another",
        tmdbId: 4762,
      },
      { id: "trier", name: "Joachim Trier", subtitle: "Sentimental Value", tmdbId: 71609 },
      { id: "coogler", name: "Ryan Coogler", subtitle: "Sinners", tmdbId: 1056121 },
    ],
  },
  {
    id: "actor",
    number: "03",
    label: "MELHOR",
    title: "ATOR",
    tmdbType: "person",
    nominees: [
      { id: "chalamet", name: "Timothée Chalamet", subtitle: "Marty Supreme", tmdbId: 1190668 },
      { id: "hawke", name: "Ethan Hawke", subtitle: "Blue Moon", tmdbId: 569 },
      { id: "moura", name: "Wagner Moura", subtitle: "The Secret Agent", tmdbId: 52583 },
      { id: "jordan", name: "Michael B. Jordan", subtitle: "Sinners", tmdbId: 135651 },
      {
        id: "dicaprio",
        name: "Leonardo DiCaprio",
        subtitle: "One Battle After Another",
        tmdbId: 6193,
      },
    ],
  },
  {
    id: "actress",
    number: "04",
    label: "MELHOR",
    title: "ATRIZ",
    tmdbType: "person",
    nominees: [
      { id: "buckley", name: "Jessie Buckley", subtitle: "Hamnet", tmdbId: 1498158 },
      {
        id: "byrne",
        name: "Rose Byrne",
        subtitle: "If I Had Legs I'd Kick You",
        tmdbId: 9827,
      },
      { id: "hudson", name: "Kate Hudson", subtitle: "Song Sung Blue", tmdbId: 11661 },
      { id: "reinsve", name: "Renate Reinsve", subtitle: "Sentimental Value", tmdbId: 1576786 },
      { id: "stone", name: "Emma Stone", subtitle: "Bugonia", tmdbId: 54693 },
    ],
  },
  {
    id: "supp-actor",
    number: "05",
    label: "MELHOR ATOR",
    title: "COADJUVANTE",
    tmdbType: "person",
    nominees: [
      {
        id: "del-toro",
        name: "Benicio del Toro",
        subtitle: "One Battle After Another",
        tmdbId: 1121,
      },
      { id: "elordi", name: "Jacob Elordi", subtitle: "Frankenstein", tmdbId: 2034418 },
      { id: "penn", name: "Sean Penn", subtitle: "One Battle After Another", tmdbId: 2228 },
      { id: "lindo", name: "Delroy Lindo", subtitle: "Sinners", tmdbId: 18792 },
      {
        id: "skarsgard",
        name: "Stellan Skarsgård",
        subtitle: "Sentimental Value",
        tmdbId: 1640,
      },
    ],
  },
  {
    id: "supp-actress",
    number: "06",
    label: "MELHOR ATRIZ",
    title: "COADJUVANTE",
    tmdbType: "person",
    nominees: [
      { id: "fanning", name: "Elle Fanning", subtitle: "Sentimental Value", tmdbId: 18050 },
      {
        id: "lilleaas",
        name: "Inga Ibsdotter Lilleaas",
        subtitle: "Sentimental Value",
        tmdbId: 1421850,
      },
      {
        id: "taylor",
        name: "Teyana Taylor",
        subtitle: "One Battle After Another",
        tmdbId: 964679,
      },
      { id: "mosaku", name: "Wunmi Mosaku", subtitle: "Sinners", tmdbId: 134774 },
      { id: "madigan", name: "Amy Madigan", subtitle: "Weapons", tmdbId: 23882 },
    ],
  },
  {
    id: "international",
    number: "07",
    label: "MELHOR FILME",
    title: "INTERNACIONAL",
    tmdbType: "movie",
    nominees: [
      { id: "secret-agent-int", name: "The Secret Agent", subtitle: "Brasil", tmdbId: 1220564 },
      {
        id: "it-was-accident",
        name: "It Was Just an Accident",
        subtitle: "França",
        tmdbId: 1456349,
      },
      {
        id: "sentimental-value-int",
        name: "Sentimental Value",
        subtitle: "Noruega",
        tmdbId: 1124566,
      },
      { id: "sirat", name: "Sirāt", subtitle: "Espanha", tmdbId: 1151272 },
      {
        id: "hind-rajab",
        name: "The Voice of Hind Rajab",
        subtitle: "Tunísia",
        tmdbId: 1480382,
      },
    ],
  },
  {
    id: "orig-screenplay",
    number: "08",
    label: "MELHOR ROTEIRO",
    title: "ORIGINAL",
    tmdbType: "movie",
    nominees: [
      { id: "blue-moon-script", name: "Blue Moon", tmdbId: 1299655 },
      { id: "accident-script", name: "It Was Just an Accident", tmdbId: 1456349 },
      { id: "marty-script", name: "Marty Supreme", tmdbId: 1317288 },
      { id: "sentimental-script", name: "Sentimental Value", tmdbId: 1124566 },
      { id: "sinners-script", name: "Sinners", tmdbId: 1233413 },
    ],
  },
  {
    id: "adapted-screenplay",
    number: "09",
    label: "MELHOR ROTEIRO",
    title: "ADAPTADO",
    tmdbType: "movie",
    nominees: [
      { id: "bugonia-script", name: "Bugonia", tmdbId: 701387 },
      { id: "frank-script", name: "Frankenstein (2025)", tmdbId: 1062722 },
      { id: "hamnet-script", name: "Hamnet", tmdbId: 858024 },
      { id: "one-battle-script", name: "One Battle After Another", tmdbId: 1054867 },
      { id: "train-script", name: "Train Dreams", tmdbId: 1241983 },
    ],
  },
  {
    id: "casting",
    number: "10",
    label: "MELHOR",
    title: "ELENCO",
    tmdbType: "movie",
    nominees: [
      { id: "hamnet-cast", name: "Hamnet", tmdbId: 858024 },
      { id: "marty-cast", name: "Marty Supreme", tmdbId: 1317288 },
      { id: "one-battle-cast", name: "One Battle After Another", tmdbId: 1054867 },
      { id: "secret-agent-cast", name: "The Secret Agent", tmdbId: 1220564 },
      { id: "sinners-cast", name: "Sinners", tmdbId: 1233413 },
    ],
  },
  {
    id: "animated",
    number: "11",
    label: "MELHOR",
    title: "ANIMAÇÃO",
    tmdbType: "movie",
    nominees: [
      { id: "kpop-demons", name: "K-Pop Demon Hunters", tmdbId: 803796 },
      { id: "zootopia2", name: "Zootopia 2", tmdbId: 1084242 },
      { id: "elio", name: "Elio", tmdbId: 1022787 },
      { id: "arc", name: "Arc" },
      { id: "little-amelie", name: "Little Amélie", tmdbId: 682012 },
    ],
  },
  {
    id: "documentary",
    number: "12",
    label: "MELHOR",
    title: "DOCUMENTÁRIO",
    tmdbType: "movie",
    nominees: [
      { id: "alabama", name: "Alabama" },
      { id: "neon-light", name: "Under the Neon Light" },
      { id: "breaking-rocks", name: "Breaking Through Rock" },
      { id: "mr-nobody", name: "Mr. Nobody Against Putin", tmdbId: 1393151 },
      { id: "perfect-neighbor", name: "The Perfect Neighbor", tmdbId: 1400782 },
    ],
  },
  {
    id: "cinematography",
    number: "13",
    label: "MELHOR",
    title: "FOTOGRAFIA",
    tmdbType: "movie",
    nominees: [
      { id: "marty-photo", name: "Marty Supreme", tmdbId: 1317288 },
      { id: "frank-photo", name: "Frankenstein (2025)", tmdbId: 1062722 },
      { id: "sinners-photo", name: "Sinners", tmdbId: 1233413 },
      { id: "one-battle-photo", name: "One Battle After Another", tmdbId: 1054867 },
      { id: "train-photo", name: "Train Dreams", tmdbId: 1241983 },
    ],
  },
  {
    id: "costume",
    number: "14",
    label: "MELHOR",
    title: "FIGURINO",
    tmdbType: "movie",
    nominees: [
      { id: "avatar-costume", name: "Avatar: Fire and Ash", tmdbId: 83533 },
      { id: "frank-costume", name: "Frankenstein (2025)", tmdbId: 1062722 },
      { id: "hamnet-costume", name: "Hamnet", tmdbId: 858024 },
      { id: "marty-costume", name: "Marty Supreme", tmdbId: 1317288 },
      { id: "sinners-costume", name: "Sinners", tmdbId: 1233413 },
    ],
  },
  {
    id: "editing",
    number: "15",
    label: "MELHOR",
    title: "MONTAGEM",
    tmdbType: "movie",
    nominees: [
      { id: "f1-edit", name: "F1", tmdbId: 911430 },
      { id: "marty-edit", name: "Marty Supreme", tmdbId: 1317288 },
      { id: "one-battle-edit", name: "One Battle After Another", tmdbId: 1054867 },
      { id: "sentimental-edit", name: "Sentimental Value", tmdbId: 1124566 },
      { id: "sinners-edit", name: "Sinners", tmdbId: 1233413 },
    ],
  },
  {
    id: "production-design",
    number: "16",
    label: "MELHOR DESIGN DE",
    title: "PRODUÇÃO",
    tmdbType: "movie",
    nominees: [
      { id: "frank-design", name: "Frankenstein (2025)", tmdbId: 1062722 },
      { id: "hamnet-design", name: "Hamnet", tmdbId: 858024 },
      { id: "marty-design", name: "Marty Supreme", tmdbId: 1317288 },
      { id: "one-battle-design", name: "One Battle After Another", tmdbId: 1054867 },
      { id: "sinners-design", name: "Sinners", tmdbId: 1233413 },
    ],
  },
  {
    id: "score",
    number: "17",
    label: "MELHOR TRILHA",
    title: "SONORA",
    tmdbType: "movie",
    nominees: [
      { id: "bugonia-score", name: "Bugonia", tmdbId: 701387 },
      { id: "frank-score", name: "Frankenstein (2025)", tmdbId: 1062722 },
      { id: "hamnet-score", name: "Hamnet", tmdbId: 858024 },
      { id: "sinners-score", name: "Sinners", tmdbId: 1233413 },
      { id: "one-battle-score", name: "One Battle After Another", tmdbId: 1054867 },
    ],
  },
  {
    id: "song",
    number: "18",
    label: "MELHOR",
    title: "CANÇÃO",
    tmdbType: "movie",
    nominees: [
      {
        id: "dear-me",
        name: "Diane Warren: Relentless",
        subtitle: '"Dear Me"',
        tmdbId: 826338,
      },
      { id: "golden", name: "K-Pop Demon Hunters", subtitle: '"Golden"', tmdbId: 803796 },
      { id: "i-lied", name: "Sinners", subtitle: '"I Lied to You"', tmdbId: 1233413 },
      { id: "sweet-dreams", name: "Viva Verdi", subtitle: '"Sweet Dreams of Joy"', tmdbId: 1358554 },
      {
        id: "train-dreams-song",
        name: "Train Dreams",
        subtitle: '"Train Dreams"',
        tmdbId: 1241983,
      },
    ],
  },
  {
    id: "makeup",
    number: "19",
    label: "MELHOR MAQUIAGEM",
    title: "E CABELO",
    tmdbType: "movie",
    nominees: [
      { id: "frank-makeup", name: "Frankenstein (2025)", tmdbId: 1062722 },
      { id: "kokuho", name: "Kokuho", tmdbId: 1379266 },
      { id: "sinners-makeup", name: "Sinners", tmdbId: 1233413 },
      { id: "smashing-machine", name: "The Smashing Machine", tmdbId: 760329 },
      { id: "ugly-stepsister", name: "The Ugly Stepsister", tmdbId: 1284120 },
    ],
  },
  {
    id: "sound",
    number: "20",
    label: "MELHOR",
    title: "SOM",
    tmdbType: "movie",
    nominees: [
      { id: "f1-sound", name: "F1", tmdbId: 911430 },
      { id: "sinners-sound", name: "Sinners", tmdbId: 1233413 },
      { id: "sirat-sound", name: "Sirāt", tmdbId: 1151272 },
      { id: "frank-sound", name: "Frankenstein (2025)", tmdbId: 1062722 },
      { id: "one-battle-sound", name: "One Battle After Another", tmdbId: 1054867 },
    ],
  },
  {
    id: "vfx",
    number: "21",
    label: "MELHORES EFEITOS",
    title: "VISUAIS",
    tmdbType: "movie",
    nominees: [
      { id: "avatar-vfx", name: "Avatar: Fire and Ash", tmdbId: 83533 },
      { id: "f1-vfx", name: "F1", tmdbId: 911430 },
      { id: "jurassic-vfx", name: "Jurassic World Rebirth", tmdbId: 1234821 },
      { id: "sinners-vfx", name: "Sinners", tmdbId: 1233413 },
      { id: "lost-bus", name: "The Lost Bus", tmdbId: 1236470 },
    ],
  },
  {
    id: "animated-short",
    number: "22",
    label: "MELHOR CURTA",
    title: "ANIMADO",
    tmdbType: "movie",
    nominees: [
      { id: "butterfly", name: "Butterfly", tmdbId: 1477292 },
      { id: "forevergreen", name: "Forevergreen", tmdbId: 1477914 },
      { id: "pearl-girl", name: "The Girl Who Cried Pearls", tmdbId: 1142149 },
      { id: "retirement-plan", name: "Retirement Plan", tmdbId: 1316745 },
      { id: "three-sisters", name: "The Three Sisters", tmdbId: 1302562 },
    ],
  },
  {
    id: "doc-short",
    number: "23",
    label: "MELHOR CURTA",
    title: "DOCUMENTÁRIO",
    tmdbType: "movie",
    nominees: [
      { id: "empty-rooms", name: "All the Empty Rooms", tmdbId: 1525091 },
      { id: "brent-renaud", name: "Armed with Only a Camera", tmdbId: 1422051 },
      { id: "children-no-more", name: "Children No More", tmdbId: 1560400 },
      { id: "devil-busy", name: "The Devil is Busy", tmdbId: 1373150 },
      { id: "perfect-strangeness", name: "Perfectly a Strangeness", tmdbId: 1278954 },
    ],
  },
  {
    id: "live-action-short",
    number: "24",
    label: "MELHOR CURTA",
    title: "LIVE ACTION",
    tmdbType: "movie",
    nominees: [
      { id: "butchers-stain", name: "Butcher's Stain", tmdbId: 1560394 },
      { id: "friend-dorothy", name: "A Friend of Dorothy", tmdbId: 1470465 },
      { id: "jane-austen", name: "Jane Austen's Period Drama", tmdbId: 1272266 },
      { id: "os-cantores", name: "Os Cantores", tmdbId: 1442908 },
      { id: "two-people", name: "Two People Exchanging Saliva", tmdbId: 1340625 },
    ],
  },
];
